sudo: false
language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - 3.5
  - pypy
  - pypy3
matrix:
  allow_failures:
    - python: 3.5
install:
  - pip install tox-travis
  - python setup.py develop
script:
  - tox
  - coverage report -m
after_script:
  coveralls --verbose
